/*
 Navicat Premium Data Transfer

 Source Server         : testing
 Source Server Type    : Oracle
 Source Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 Source Host           : localhost:1521
 Source Schema         : C##LAB_INVENTORY_3

 Target Server Type    : Oracle
 Target Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 File Encoding         : 65001

 Date: 12/09/2023 09:53:45
*/


-- ----------------------------
-- Table structure for DUES
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."DUES";
CREATE TABLE "C##LAB_INVENTORY_3"."DUES" (
  "DUE_ID" NUMBER VISIBLE NOT NULL,
  "EQUIPMENT_ID" NUMBER VISIBLE NOT NULL,
  "REQ_ID" NUMBER VISIBLE NOT NULL,
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "DUE_DATE" DATE VISIBLE,
  "DUE_STATUS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DUES
-- ----------------------------

-- ----------------------------
-- Table structure for EQUIPMENTS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS";
CREATE TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" (
  "EQUIPMENT_ID" NUMBER VISIBLE NOT NULL,
  "EQUIPMENT_NAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "TYPE" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "COST" NUMBER VISIBLE,
  "DESCRIPT" VARCHAR2(1000 BYTE) VISIBLE NOT NULL,
  "PERMIT" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of EQUIPMENTS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS" VALUES ('1', 'Breadboard', 'Hardware', '90', 'A 400-point solderless breadboard is an electronic prototyping tool used to build and test circuits without the need for soldering.', '1');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS" VALUES ('2', 'Arduino Uno', 'Hardware', '1100', 'Microcontroller : ATmega328 Operating', '2');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS" VALUES ('3', 'LED', 'Hardware', '5', 'A light emitting diode(led) is semiconductor device which emits light when current pass through it', '1');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS" VALUES ('4', 'Atmega32', 'Hardware', '800', 'The low-power, high-performance Microchip 8-bit AVR&reg', '2');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS" VALUES ('5', 'IC 7408', 'Hardware', '20', 'The 7408 integrated circuit is a QUAD 2-Input AND GATES and contains four independent gates each of which performs the logic AND function', '1');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS" VALUES ('6', 'Raspberry Pi 4', 'Hardware', '25000', 'Raspberry Pi is a small single board computer. By connecting peripherals like Keyboard, mouse, display to the Raspberry Pi, it will act as a mini personal computer.', '2');

-- ----------------------------
-- Table structure for EQUIPMENTS_IN_LOCATIONS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS";
CREATE TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" (
  "EQUIPMENT_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "QUANTITY" NUMBER VISIBLE,
  "LOAN" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of EQUIPMENTS_IN_LOCATIONS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('1', '1', '3', '0');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('1', '2', '5', '1');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('2', '1', '5', '0');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('4', '2', '8', '2');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('6', '2', '3', '0');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('3', '1', '50', '12');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('3', '2', '40', '5');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('5', '1', '15', '3');

-- ----------------------------
-- Table structure for EQUIPMENTS_IN_REQUESTS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS";
CREATE TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" (
  "EQUIPMENT_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "REQ_ID" NUMBER VISIBLE NOT NULL,
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "QUANTITY" NUMBER VISIBLE,
  "REQ_STATUS" NUMBER VISIBLE,
  "MANDATORY" NUMBER VISIBLE,
  "WAIT_TIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of EQUIPMENTS_IN_REQUESTS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" VALUES ('2', '1', '9', '24', '1', '1', NULL, TO_DATE('2023-09-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" VALUES ('1', '2', '8', '1', '1', '0', NULL, TO_DATE('2023-09-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" VALUES ('1', '1', '5', '1', '2', '1', NULL, TO_DATE('2023-09-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" VALUES ('1', '1', '6', '1', '1', '0', NULL, TO_DATE('2023-09-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" VALUES ('1', '1', '7', '1', '1', '0', NULL, TO_DATE('2023-09-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for LOCATIONS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."LOCATIONS";
CREATE TABLE "C##LAB_INVENTORY_3"."LOCATIONS" (
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_NAME" VARCHAR2(30 BYTE) VISIBLE,
  "ROOM_NO" NUMBER VISIBLE,
  "LAB_ASSISTANT" NUMBER VISIBLE,
  "LAB_SUPERVISOR" NUMBER VISIBLE,
  "TYPE" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of LOCATIONS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."LOCATIONS" VALUES ('1', 'DL', '101', '22', '2', 'Hardware');
INSERT INTO "C##LAB_INVENTORY_3"."LOCATIONS" VALUES ('2', 'IL', '102', '23', '21', 'Hardware');
INSERT INTO "C##LAB_INVENTORY_3"."LOCATIONS" VALUES ('3', 'DBL', '401', '22', '25', 'Software');
INSERT INTO "C##LAB_INVENTORY_3"."LOCATIONS" VALUES ('4', 'CL', '103', '23', '26', 'Software');

-- ----------------------------
-- Table structure for REQUESTS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."REQUESTS";
CREATE TABLE "C##LAB_INVENTORY_3"."REQUESTS" (
  "REQ_ID" NUMBER VISIBLE NOT NULL,
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "REQ_TIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of REQUESTS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."REQUESTS" VALUES ('9', '24', TO_DATE('2023-09-12 09:32:20', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "C##LAB_INVENTORY_3"."REQUESTS" VALUES ('8', '1', TO_DATE('2023-09-12 00:26:43', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "C##LAB_INVENTORY_3"."REQUESTS" VALUES ('5', '1', TO_DATE('2023-09-12 00:08:42', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "C##LAB_INVENTORY_3"."REQUESTS" VALUES ('6', '1', TO_DATE('2023-09-12 00:10:10', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "C##LAB_INVENTORY_3"."REQUESTS" VALUES ('7', '1', TO_DATE('2023-09-12 00:23:36', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."USERS";
CREATE TABLE "C##LAB_INVENTORY_3"."USERS" (
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "FIRST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "ROLE" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "PHONE_NO" VARCHAR2(20 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('22', 'aislam', 'Ainal', 'Islam', 'ais@gmail.com', 'lab1', 'Lab Assistant', '01942795390');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('3', '1905091', 'Sadia', 'Tabassum', 'sadia@gmail.com', 'abcd', 'Student', '12345678');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('24', '1905099', 'Alina', 'Zaman', 'zmalina98@gmail.com', '1234', 'Student', '01582953726');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('25', 'ht', 'Tahmid', 'Hasan', 'ht@gmail.com', 'abcd', 'Teacher', '12345678901');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('23', 'shaq', 'Shamsul', 'Haque', 'shaq@gmail.com', 'shaq', 'Lab Assistant', '01953682049');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('26', 'mmm', 'Md. Masum', 'Mushfiq', 'mmm@gmail.com', 'abcd', 'Teacher', '01234567891');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('1', '1905103', 'Mayesha', 'Rashid', 'mayesha1599@gmail.com', 'abcd', 'Student', '01814903467');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('2', 'mtz', 'Md.', 'Toufiquzzaman', 'toufiquzzamanpranto@gmail.com', 'abcd', 'Teacher', '01234567891');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('21', 'tareqmahmood', 'Tareq', 'Mahmud', 'tm@gmail.com', '1234', 'Teacher', '12345678');

-- ----------------------------
-- Function structure for ADD_REQUEST
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "C##LAB_INVENTORY_3"."ADD_REQUEST" AS
BEGIN
    /*SELECT EQUIPMENT_ID INTO EID
    FROM EQUIPMENTS
    WHERE EQUIPMENT_NAME = ENAME;

    SELECT LOCATION_ID INTO LID
    FROM LOCATION
    WHERE LOCATION_NAME = LNAME;

    INSERT INTO REQUESTS(USER_ID, REQ_TIME) VALUES(UID, SYSDATE);

    SELECT REQ_ID INTO RID
    FROM REQUESTS
    WHERE USER_ID = UID AND
    REQ_TIME = SYSDATE;

    INSERT INTO EQUIPMENTS_IN_REQUESTS(EQUIPMENT_ID, LOCATION_ID, REQ_ID, USER_ID, QUANTITY, REQ_STATUS, WAIT_TIME)
    VALUES(EID, LID, RID, UID, EQUANTITY, 0, WAIT_DATE); -- Add a semicolon here*/
END;
/

-- ----------------------------
-- Function structure for CREATE_REQ
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "C##LAB_INVENTORY_3"."CREATE_REQ" AS
BEGIN
    SELECT EQUIPMENT_ID INTO EID
    FROM EQUIPMENTS
    WHERE EQUIPMENT_NAME = ENAME;

    SELECT LOCATION_ID INTO LID
    FROM LOCATIONS
    WHERE LOCATION_NAME = LNAME;
		
		RID:= REQUEST_SEQUENCE.NEXTVAL;

    INSERT INTO REQUESTS(REQ_ID,USER_ID, REQ_TIME) VALUES(RID,USID, SYSDATE);

    /*SELECT REQ_ID INTO RID
    FROM REQUESTS
    WHERE USER_ID = USID AND
    REQ_TIME = SYSDATE;*/

    INSERT INTO EQUIPMENTS_IN_REQUESTS(EQUIPMENT_ID, LOCATION_ID, REQ_ID, USER_ID, QUANTITY, REQ_STATUS, WAIT_TIME)
    VALUES(EID, LID, RID, USID, EQUANTITY, 0, TO_DATE(WAIT_DATE,'DD-MON-YYYY')); -- Add a semicolon here*/
END;
/

-- ----------------------------
-- Sequence structure for EQUIPMENT_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##LAB_INVENTORY_3"."EQUIPMENT_SEQUENCE";
CREATE SEQUENCE "C##LAB_INVENTORY_3"."EQUIPMENT_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for REQUEST_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##LAB_INVENTORY_3"."REQUEST_SEQUENCE";
CREATE SEQUENCE "C##LAB_INVENTORY_3"."REQUEST_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for USER_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##LAB_INVENTORY_3"."USER_SEQUENCE";
CREATE SEQUENCE "C##LAB_INVENTORY_3"."USER_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Checks structure for table DUES
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010641" CHECK ("DUE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010642" CHECK ("EQUIPMENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010643" CHECK ("REQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010644" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010645" CHECK ("LOCATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EQUIPMENTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010599" PRIMARY KEY ("EQUIPMENT_ID");

-- ----------------------------
-- Checks structure for table EQUIPMENTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010595" CHECK ("EQUIPMENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010596" CHECK ("EQUIPMENT_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010597" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010598" CHECK ("DESCRIPT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table EQUIPMENTS
-- ----------------------------
CREATE TRIGGER "C##LAB_INVENTORY_3"."EQUIPMENT_BIN" BEFORE INSERT ON "C##LAB_INVENTORY_3"."EQUIPMENTS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
IF :NEW.EQUIPMENT_ID IS NULL
THEN
:NEW.EQUIPMENT_ID:=EQUIPMENT_SEQUENCE.NEXTVAL;
END IF;
END;
/

-- ----------------------------
-- Primary Key structure for table EQUIPMENTS_IN_LOCATIONS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" ADD CONSTRAINT "SYS_C0010602" PRIMARY KEY ("EQUIPMENT_ID", "LOCATION_ID");

-- ----------------------------
-- Primary Key structure for table EQUIPMENTS_IN_REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" ADD CONSTRAINT "SYS_C0010638" PRIMARY KEY ("REQ_ID", "USER_ID", "EQUIPMENT_ID", "LOCATION_ID");

-- ----------------------------
-- Primary Key structure for table LOCATIONS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."LOCATIONS" ADD CONSTRAINT "SYS_C0010601" PRIMARY KEY ("LOCATION_ID");

-- ----------------------------
-- Checks structure for table LOCATIONS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."LOCATIONS" ADD CONSTRAINT "SYS_C0010600" CHECK ("LOCATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."REQUESTS" ADD CONSTRAINT "SYS_C0010636" PRIMARY KEY ("REQ_ID", "USER_ID");

-- ----------------------------
-- Checks structure for table REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."REQUESTS" ADD CONSTRAINT "SYS_C0010635" CHECK ("REQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010592" PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Uniques structure for table USERS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010593" UNIQUE ("USERNAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010594" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010586" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010587" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010588" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010589" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010590" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010591" CHECK ("PHONE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table USERS
-- ----------------------------
CREATE TRIGGER "C##LAB_INVENTORY_3"."USER_BIN" BEFORE INSERT ON "C##LAB_INVENTORY_3"."USERS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
IF :NEW.USER_ID IS NULL
THEN
:NEW.USER_ID:=USER_SEQUENCE.NEXTVAL;
END IF;
END;
/

-- ----------------------------
-- Foreign Keys structure for table DUES
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010646" FOREIGN KEY ("REQ_ID", "USER_ID", "EQUIPMENT_ID", "LOCATION_ID") REFERENCES "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" ("REQ_ID", "USER_ID", "EQUIPMENT_ID", "LOCATION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EQUIPMENTS_IN_LOCATIONS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" ADD CONSTRAINT "SYS_C0010603" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "C##LAB_INVENTORY_3"."EQUIPMENTS" ("EQUIPMENT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" ADD CONSTRAINT "SYS_C0010604" FOREIGN KEY ("LOCATION_ID") REFERENCES "C##LAB_INVENTORY_3"."LOCATIONS" ("LOCATION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EQUIPMENTS_IN_REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" ADD CONSTRAINT "SYS_C0010639" FOREIGN KEY ("REQ_ID", "USER_ID") REFERENCES "C##LAB_INVENTORY_3"."REQUESTS" ("REQ_ID", "USER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" ADD CONSTRAINT "SYS_C0010640" FOREIGN KEY ("EQUIPMENT_ID", "LOCATION_ID") REFERENCES "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" ("EQUIPMENT_ID", "LOCATION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."REQUESTS" ADD CONSTRAINT "SYS_C0010637" FOREIGN KEY ("USER_ID") REFERENCES "C##LAB_INVENTORY_3"."USERS" ("USER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
