/*
 Navicat Premium Data Transfer

 Source Server         : testing
 Source Server Type    : Oracle
 Source Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 Source Host           : localhost:1521
 Source Schema         : C##LAB_INVENTORY_3

 Target Server Type    : Oracle
 Target Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 File Encoding         : 65001

 Date: 11/09/2023 21:52:25
*/


-- ----------------------------
-- Table structure for DUES
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."DUES";
CREATE TABLE "C##LAB_INVENTORY_3"."DUES" (
  "DUE_ID" NUMBER VISIBLE NOT NULL,
  "EQUIPMENT_ID" NUMBER VISIBLE NOT NULL,
  "REQ_ID" NUMBER VISIBLE NOT NULL,
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "DUE_DATE" DATE VISIBLE,
  "DUE_STATUS" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DUES
-- ----------------------------

-- ----------------------------
-- Table structure for EQUIPMENTS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS";
CREATE TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" (
  "EQUIPMENT_ID" NUMBER VISIBLE NOT NULL,
  "EQUIPMENT_NAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "TYPE" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
  "COST" NUMBER VISIBLE,
  "DESCRIPT" VARCHAR2(1000 BYTE) VISIBLE NOT NULL,
  "PERMIT" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of EQUIPMENTS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS" VALUES ('1', 'Breadboard', 'Hardware', '90', 'A 400-point solderless breadboard is an electronic prototyping tool used to build and test circuits without the need for soldering.', '1');

-- ----------------------------
-- Table structure for EQUIPMENTS_IN_LOCATIONS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS";
CREATE TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" (
  "EQUIPMENT_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "QUANTITY" NUMBER VISIBLE,
  "LOAN" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of EQUIPMENTS_IN_LOCATIONS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('1', '1', '3', '0');
INSERT INTO "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" VALUES ('1', '2', '5', '1');

-- ----------------------------
-- Table structure for EQUIPMENTS_IN_REQUESTS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS";
CREATE TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" (
  "EQUIPMENT_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "REQ_ID" NUMBER VISIBLE NOT NULL,
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "QUANTITY" NUMBER VISIBLE,
  "REQ_STATUS" NUMBER VISIBLE,
  "MANDATORY" NUMBER VISIBLE,
  "WAIT_TIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of EQUIPMENTS_IN_REQUESTS
-- ----------------------------

-- ----------------------------
-- Table structure for LOCATIONS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."LOCATIONS";
CREATE TABLE "C##LAB_INVENTORY_3"."LOCATIONS" (
  "LOCATION_ID" NUMBER VISIBLE NOT NULL,
  "LOCATION_NAME" VARCHAR2(30 BYTE) VISIBLE,
  "ROOM_NO" NUMBER VISIBLE,
  "LAB_ASSISTANT" NUMBER VISIBLE,
  "LAB_SUPERVISOR" NUMBER VISIBLE,
  "TYPE" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of LOCATIONS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."LOCATIONS" VALUES ('1', 'DL', '101', NULL, NULL, NULL);
INSERT INTO "C##LAB_INVENTORY_3"."LOCATIONS" VALUES ('2', 'IL', '102', NULL, NULL, NULL);

-- ----------------------------
-- Table structure for REQUESTS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."REQUESTS";
CREATE TABLE "C##LAB_INVENTORY_3"."REQUESTS" (
  "REQ_ID" NUMBER VISIBLE NOT NULL,
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "REQ_TIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of REQUESTS
-- ----------------------------

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "C##LAB_INVENTORY_3"."USERS";
CREATE TABLE "C##LAB_INVENTORY_3"."USERS" (
  "USER_ID" NUMBER VISIBLE NOT NULL,
  "USERNAME" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
  "FIRST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "LAST_NAME" VARCHAR2(50 BYTE) VISIBLE,
  "EMAIL" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "ROLE" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "PHONE_NO" VARCHAR2(20 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('3', '1905091', 'Sadia', 'Tabassum', 'sadia@gmail.com', 'abcd', 'Student', '12345678');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('1', '1905103', 'Mayesha', 'Rashid', 'mayesha1599@gmail.com', 'abcd', 'Student', '01814903467');
INSERT INTO "C##LAB_INVENTORY_3"."USERS" VALUES ('2', 'mtz', 'Md.', 'Toufiquzzaman', 'toufiquzzamanpranto@gmail.com', 'abcd', 'Teacher', '01234567891');

-- ----------------------------
-- Sequence structure for EQUIPMENT_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##LAB_INVENTORY_3"."EQUIPMENT_SEQUENCE";
CREATE SEQUENCE "C##LAB_INVENTORY_3"."EQUIPMENT_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for USER_SEQUENCE
-- ----------------------------
DROP SEQUENCE "C##LAB_INVENTORY_3"."USER_SEQUENCE";
CREATE SEQUENCE "C##LAB_INVENTORY_3"."USER_SEQUENCE" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Checks structure for table DUES
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010625" CHECK ("DUE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010626" CHECK ("EQUIPMENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010627" CHECK ("REQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010628" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010629" CHECK ("LOCATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EQUIPMENTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010599" PRIMARY KEY ("EQUIPMENT_ID");

-- ----------------------------
-- Checks structure for table EQUIPMENTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010595" CHECK ("EQUIPMENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010596" CHECK ("EQUIPMENT_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010597" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS" ADD CONSTRAINT "SYS_C0010598" CHECK ("DESCRIPT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table EQUIPMENTS
-- ----------------------------
CREATE TRIGGER "C##LAB_INVENTORY_3"."EQUIPMENT_BIN" BEFORE INSERT ON "C##LAB_INVENTORY_3"."EQUIPMENTS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
IF :NEW.EQUIPMENT_ID IS NULL
THEN
:NEW.EQUIPMENT_ID:=EQUIPMENT_SEQUENCE.NEXTVAL;
END IF;
END;
/

-- ----------------------------
-- Primary Key structure for table EQUIPMENTS_IN_LOCATIONS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" ADD CONSTRAINT "SYS_C0010602" PRIMARY KEY ("EQUIPMENT_ID", "LOCATION_ID");

-- ----------------------------
-- Primary Key structure for table EQUIPMENTS_IN_REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" ADD CONSTRAINT "SYS_C0010622" PRIMARY KEY ("REQ_ID", "USER_ID", "EQUIPMENT_ID", "LOCATION_ID");

-- ----------------------------
-- Primary Key structure for table LOCATIONS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."LOCATIONS" ADD CONSTRAINT "SYS_C0010601" PRIMARY KEY ("LOCATION_ID");

-- ----------------------------
-- Checks structure for table LOCATIONS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."LOCATIONS" ADD CONSTRAINT "SYS_C0010600" CHECK ("LOCATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."REQUESTS" ADD CONSTRAINT "SYS_C0010618" PRIMARY KEY ("REQ_ID", "USER_ID");

-- ----------------------------
-- Checks structure for table REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."REQUESTS" ADD CONSTRAINT "SYS_C0010617" CHECK ("REQ_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010592" PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Uniques structure for table USERS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010593" UNIQUE ("USERNAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010594" UNIQUE ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010586" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010587" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010588" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010589" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010590" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."USERS" ADD CONSTRAINT "SYS_C0010591" CHECK ("PHONE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table USERS
-- ----------------------------
CREATE TRIGGER "C##LAB_INVENTORY_3"."USER_BIN" BEFORE INSERT ON "C##LAB_INVENTORY_3"."USERS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
IF :NEW.USER_ID IS NULL
THEN
:NEW.USER_ID:=USER_SEQUENCE.NEXTVAL;
END IF;
END;
/

-- ----------------------------
-- Foreign Keys structure for table DUES
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."DUES" ADD CONSTRAINT "SYS_C0010630" FOREIGN KEY ("REQ_ID", "USER_ID", "EQUIPMENT_ID", "LOCATION_ID") REFERENCES "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" ("REQ_ID", "USER_ID", "EQUIPMENT_ID", "LOCATION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EQUIPMENTS_IN_LOCATIONS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" ADD CONSTRAINT "SYS_C0010603" FOREIGN KEY ("EQUIPMENT_ID") REFERENCES "C##LAB_INVENTORY_3"."EQUIPMENTS" ("EQUIPMENT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" ADD CONSTRAINT "SYS_C0010604" FOREIGN KEY ("LOCATION_ID") REFERENCES "C##LAB_INVENTORY_3"."LOCATIONS" ("LOCATION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EQUIPMENTS_IN_REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" ADD CONSTRAINT "SYS_C0010623" FOREIGN KEY ("REQ_ID", "USER_ID") REFERENCES "C##LAB_INVENTORY_3"."REQUESTS" ("REQ_ID", "USER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_REQUESTS" ADD CONSTRAINT "SYS_C0010624" FOREIGN KEY ("EQUIPMENT_ID", "LOCATION_ID") REFERENCES "C##LAB_INVENTORY_3"."EQUIPMENTS_IN_LOCATIONS" ("EQUIPMENT_ID", "LOCATION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table REQUESTS
-- ----------------------------
ALTER TABLE "C##LAB_INVENTORY_3"."REQUESTS" ADD CONSTRAINT "SYS_C0010619" FOREIGN KEY ("USER_ID") REFERENCES "C##LAB_INVENTORY_3"."USERS" ("USER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
